name: Build
on:
  push:
    branches:
      - 'main'
  pull_request:
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get npm cache directory
        id: npm-cache-dir
        shell: bash
        run: echo "dir=$(npm config get cache)" >> ${GITHUB_OUTPUT}

      - uses: actions/cache@v3
        id: npm-cache
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            node-
      
      - name: Install dependencies
        run: npm ci
    
      - name: Cypress tests 🧪
        uses: cypress-io/github-action@v6
        with:
          install: false
          browser: chrome

      - name: Upload test screenshots
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          if-no-files-found: ignore

      - name: Upload test videos
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos
          if-no-files-found: ignore

      - name: Upload test snapshots
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: cypress-snapshots
          path: cypress/snapshots/**/__diff_output__/*.png
          if-no-files-found: ignore